const affiliateAliases={order_id:['注文番号','注文ID','成果ID','注文識別子'],order_date:['注文日','注文日時'],sale_date:['成果発生日','成果発生日時','発生日','日付'],itemCode:['itemCode','商品コード'],itemUrl:['商品URL'],affiliateUrl:['affiliateUrl','アフィリエイトURL'],itemName:['商品名'],shopName:['ショップ名','ショップ','店舗名'],genre:['商品ジャンル','ジャンル'],sales_amount:['売上金額','売上額','売上'],reward_amount:['成果報酬','成果報酬額','報酬額'],sales_count:['成果件数','売上件数','注文件数'],clicks:['クリック数'],status:['ステータス','成果ステータス','状態']};
function affiliateCsvError(m){throw Error(m)}
function affiliateParseCsv(text){
 if(typeof text!=='string'||text.length>400000)affiliateCsvError('CSVは400KB以内に分割してください');
 const rows=[];let row=[],value='',quoted=false,closed=false; text=text.replace(/^\uFEFF/,'');
 for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'){if(text[i+1]==='"'){value+='"';i++}else{quoted=false;closed=true}}else value+=c;continue}
 if(c==='"'){if(value||closed)affiliateCsvError('CSVの引用符を確認してください');quoted=true}else if(c===','||c==='\n'||c==='\r'){row.push(value);value='';closed=false;if(c!==','){if(c==='\r'&&text[i+1]==='\n')i++;if(row.some(x=>x.trim()))rows.push(row);row=[]}}else{if(closed&&c.trim())affiliateCsvError('CSVの区切りを確認してください');value+=c}}
 if(quoted)affiliateCsvError('CSVの引用符が閉じていません');if(value||row.length){row.push(value);if(row.some(x=>x.trim()))rows.push(row)}
 if(rows.length<2||rows.length>1001)affiliateCsvError('見出しと1〜1000行の商品明細が必要です');const [headers,...data]=rows;if(new Set(headers.map(s=>String(s).normalize('NFKC').replace(/\s+/g,'').toLowerCase())).size!==headers.length)affiliateCsvError('重複した列名があります');if(data.some(r=>r.length!==headers.length))affiliateCsvError('CSVの列数が一致しません');return {headers,rows:data};
}
'use strict';
const affiliateLabels={order_id:'注文識別子',order_date:'注文日',sale_date:'成果発生日／日付',itemCode:'itemCode',itemUrl:'商品URL',affiliateUrl:'アフィリエイトURL',itemName:'商品名',shopName:'ショップ',genre:'ジャンル',sales_amount:'売上金額',reward_amount:'成果報酬',sales_count:'成果件数',clicks:'クリック数',status:'ステータス'};
let affiliateFileText=null,affiliateReady=null,affiliateBusy=false;
const affiliatePanel=node('details','affiliate-panel'),affiliateHeading=node('summary','','分析・楽天アフィリエイト実績を取り込む');affiliatePanel.append(affiliateHeading);
const affiliateSection=node('section','affiliate-section');affiliatePanel.append(affiliateSection);document.querySelector('footer').before(affiliatePanel);
affiliateSection.append(node('h2','','成果レポート'),node('p','','公式レポートのCSVを選び、列の対応と取得日時を確認してください。元CSVは公開しません。商品一致だけでROOM経由の成果とは断定しません。'));
const affiliateRead=node('button','quiet','分析を表示（GitHubログイン）'),affiliateResult=node('div','affiliate-results'),affiliateNotice=node('p','','');affiliateNotice.setAttribute('role','status');affiliateSection.append(affiliateRead,affiliateResult);
const affiliateFile=node('input','');affiliateFile.type='file';affiliateFile.accept='.csv,text/csv';affiliateFile.setAttribute('aria-label','公式レポートCSV');
const affiliateKind=node('select','');affiliateKind.setAttribute('aria-label','レポート形式');for(const [v,t]of [['orders','注文詳細（商品明細）'],['daily_clicks','商品別・日次クリック（集計期間の重複不可）']]){const o=node('option','',t);o.value=v;affiliateKind.append(o)}
const affiliateEncoding=node('select','');affiliateEncoding.setAttribute('aria-label','CSV文字コード');for(const v of ['utf-8','shift_jis']){const o=node('option','',v==='utf-8'?'UTF-8':'Shift_JIS');o.value=v;affiliateEncoding.append(o)}
const affiliateAsOf=node('input','');affiliateAsOf.type='datetime-local';affiliateAsOf.setAttribute('aria-label','レポートを取得した日時');
const affiliateColumns=node('div','affiliate-columns'),affiliatePreview=node('button','quiet','内容を確認'),affiliateSave=node('button','','確認した内容を取り込む');affiliatePreview.disabled=true;affiliateSave.disabled=true;
for(const [label,control]of [['CSV',affiliateFile],['文字コード',affiliateEncoding],['形式',affiliateKind],['レポートを取得した日時',affiliateAsOf]]){const l=node('label','affiliate-label',label);l.append(control);affiliateSection.append(l)}
affiliateSection.append(affiliateColumns,affiliatePreview,affiliateSave,affiliateNotice);
function affiliateLock(lock){affiliateBusy=lock;for(const c of affiliateSection.querySelectorAll('input,select,button'))c.disabled=lock;if(!lock){affiliatePreview.disabled=!affiliateFileText;affiliateSave.disabled=!affiliateReady}}
function affiliateInvalidate(){affiliateReady=null;affiliateSave.disabled=true;}
async function affiliateLoadFile(){affiliateInvalidate();try{const f=affiliateFile.files[0];if(!f)return;if(f.size>400000)throw Error('400KB以内に分割してください');affiliateFileText=new TextDecoder(affiliateEncoding.value,{fatal:true}).decode(await f.arrayBuffer());const parsed=affiliateParseCsv(affiliateFileText);affiliateColumns.replaceChildren(node('p','','空欄の項目は未取得（null）。商品別でないクリックや合計行は取り込まないでください。'));for(const [key,label]of Object.entries(affiliateLabels)){const l=node('label','affiliate-label',label),select=node('select','');select.dataset.field=key;select.setAttribute('aria-label',label+'の列');const blank=node('option','','未取得');blank.value='';select.append(blank);for(const h of parsed.headers){const o=node('option','',h);o.value=h;select.append(o)}select.value=parsed.headers.find(h=>affiliateAliases[key].some(a=>a.normalize('NFKC').replace(/\s/g,'').toLowerCase()===h.normalize('NFKC').replace(/\s/g,'').toLowerCase()))||'';select.onchange=affiliateInvalidate;l.append(select);affiliateColumns.append(l)}affiliatePreview.disabled=false;affiliateNotice.textContent=`${parsed.rows.length}行。列の対応と取得日時を確認してください。`;}catch(e){affiliateFileText=null;affiliatePreview.disabled=true;affiliateNotice.textContent='読み込めませんでした。'+e.message}}
affiliateFile.onchange=affiliateLoadFile;affiliateEncoding.onchange=affiliateLoadFile;affiliateKind.onchange=affiliateInvalidate;affiliateAsOf.onchange=affiliateInvalidate;
function affiliatePayload(){if(!affiliateFileText||!affiliateAsOf.value)throw Error('CSVとレポート取得日時を指定してください');return {csv:affiliateFileText,kind:affiliateKind.value,report_as_of:new Date(affiliateAsOf.value).toISOString(),mapping:Object.fromEntries([...affiliateColumns.querySelectorAll('select')].map(s=>[s.dataset.field,s.value]))}}
function affiliateCall(command,payload,success){affiliateLock(true);affiliateNotice.textContent='確認中…';const started=popup(command,payload,r=>{affiliateLock(false);success(r)},e=>{affiliateLock(false);affiliateNotice.textContent=e});if(!started){affiliateLock(false);affiliateNotice.textContent='開いている認証画面を確認してください。'}}
affiliatePreview.onclick=()=>{try{const payload=affiliatePayload();affiliateCall('affiliate-preview',payload,r=>{affiliateReady=r.status==='ALREADY_IMPORTED'?null:payload;affiliateSave.disabled=!affiliateReady;affiliateNotice.textContent=r.status==='ALREADY_IMPORTED'?'このCSVは取込済みです。':`追加 ${r.summary.added} / 更新 ${r.summary.updated} / 変更なし ${r.summary.unchanged} / 照合待ち ${r.summary.unmatched} / 競合 ${r.conflicts}。照合待ち・競合は自動加算しません。`;affiliateUnmatched(r.unmatched||[])})}catch(e){affiliateNotice.textContent=e.message}};
affiliateSave.onclick=()=>{if(!affiliateReady||affiliateBusy)return;affiliateCall('affiliate-import',affiliateReady,r=>{affiliateNotice.textContent=r.status==='ALREADY_IMPORTED'?'取込済みのため再加算しませんでした。':'保存・無料分析・翌日選定への反映を完了しました。';affiliateFileText=null;affiliateReady=null;affiliateFile.value='';affiliateColumns.replaceChildren();affiliatePreview.disabled=true;affiliateSave.disabled=true;if(r.analysis)affiliateRender({analysis:r.analysis})})};
affiliateRead.onclick=()=>affiliateCall('affiliate-read',{},r=>{affiliateRender(r);affiliateNotice.textContent='取込済みデータのみ表示しています。'});
function affiliateUnmatched(rows){const old=affiliateResult.querySelector('.affiliate-unmatched');if(old)old.remove();if(!rows.length)return;const d=node('details','affiliate-unmatched'),s=node('summary','',`照合待ち ${rows.length}件`);d.append(s);for(const r of rows.slice(0,100))d.append(node('p','',`${r.itemName||'商品名なし'} / ${r.shopName||'ショップ不明'}：${r.reason||'UNMATCHED'}`));affiliateResult.append(d)}
function affiliateRender(r){const a=r.analysis,t=a.totals;affiliateResult.replaceChildren();const cards=node('div','affiliate-totals');for(const [k,label]of [['sales_count','成果件数（確定＋未確定）'],['sales_amount','売上（取消除外）'],['reward_amount','成果報酬（確定＋未確定）'],['confirmed_orders','確定'],['pending_orders','未確定'],['cancelled_orders','キャンセル']]){const c=node('div','',label);c.append(node('strong','',t[k]==null?'未取得':Number(t[k]).toLocaleString('ja-JP')+(['sales_amount','reward_amount'].includes(k)?'円':'件')));cards.append(c)}affiliateResult.append(cards,node('p','','取り込んだ明細の範囲だけの集計です。未掲載商品を売上0とはみなしません。'));
 for(const row of a.items.filter(x=>x.sales_count>0)){affiliateResult.append(node('p','',`${row.itemName}：成果 ${row.sales_count}件 / 報酬 ${row.reward_amount==null?'未取得':row.reward_amount+'円'}`))}
 for(const [dim,label]of [['category','カテゴリ'],['price_band','価格帯'],['discovery_item','発見性枠']]){const d=node('details',''),s=node('summary','',label+'別');d.append(s);for(const [key,v]of Object.entries(r.summary?.[dim]||{}))d.append(node('p','',`${key}：${v.sample_size}商品 / ${v.status==='INSUFFICIENT_DATA'?'データ不足':'参考傾向'} / 成果 ${v.metrics.sales_count?.total??'未取得'} / 報酬 ${v.metrics.reward_amount?.total??'未取得'}`));affiliateResult.append(d)}affiliateUnmatched(r.unmatched||[]);}
