'use strict';
const base='http://127.0.0.1:8767';let token='',pending='',busy=false,started=0,timer;
const $=s=>document.querySelector(s),labels={READY_TO_POST:'投稿準備OK',POSTED:'投稿済み',SOLD_OUT:'売り切れ',NEEDS_REVIEW:'要確認',DISCONTINUED:'販売終了'};
function message(s){$('#notice').textContent=s}
async function api(path,body){const r=await fetch(base+path,{method:body?'POST':'GET',headers:{'X-Yua-Session':token,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,cache:'no-store'});const x=await r.json();if(!r.ok)throw Error(x.error||'接続を確認してください');return x}
function node(tag,cls,text){const e=document.createElement(tag);e.className=cls;if(text!=null)e.textContent=text;return e}
function fresh(c){const age=Date.now()-Date.parse(c.last_stock_checked_at);return c.canPost&&age>=0&&age<=900000&&!busy}
function timeLabel(t){return t?new Date(t).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'}):'未確認'}
function render(data){$('#cards').replaceChildren();let done=0,ready=0;for(const c of data.cards){if(c.status==='POSTED')done++;if(fresh(c))ready++;const card=node('article','card'),top=node('div','card-top');const img=node('img','image');img.alt=c.itemName;img.loading='lazy';try{const u=new URL(c.imageUrl);if(u.protocol==='https:'&&(u.hostname.endsWith('.rakuten.co.jp')||u.hostname.endsWith('.r10s.jp')))img.src=u.href}catch(e){}top.append(img);const meta=node('div','');meta.append(node('p','category',c.category||''),node('h2','name',c.itemName),node('p','shop',c.shopName||'ショップ確認待ち'));top.append(meta);card.append(top,node('p','price',c.itemPrice?`${Number(c.itemPrice).toLocaleString()}円`:'価格確認待ち'),node('p','shipping',c.shippingInformation?.label||'送料確認待ち'),node('p','hint',c.shippingNote));const badge=node('span','badge '+(c.status==='POSTED'?'posted':fresh(c)?'':'hold'),c.status==='READY_TO_POST'&&!fresh(c)?'最新確認が必要':labels[c.status]||c.status);card.append(badge,node('div','check-time',`在庫確認：${timeLabel(c.last_stock_checked_at)}`));for(const reason of c.reasons||[])card.append(node('p','hint error',reason));card.append(node('div','body',c.roomText),node('p','tags',(c.hashtags||[]).join(' ')));const actions=node('div','actions');const open=node('button','','楽天商品を開く'),copy=node('button','quiet','投稿文をコピー'),posted=node('button','posted-button',c.status==='POSTED'?'投稿済み ✓':'投稿済みにする');open.disabled=copy.disabled=posted.disabled=!fresh(c);open.onclick=()=>{if(!fresh(c))return message('最新情報を確認してください');const u=new URL(c.itemUrl);if(u.protocol==='https:'&&u.hostname==='item.rakuten.co.jp')window.open(u.href,'_blank','noopener,noreferrer')};copy.onclick=async()=>{if(!fresh(c))return message('最新情報を確認してください');try{await navigator.clipboard.writeText(c.fullPostText);copy.textContent='コピーしました ✓';setTimeout(()=>copy.textContent='投稿文をコピー',1800)}catch(e){message('コピーできませんでした。ブラウザのクリップボード権限を確認してください。')}};posted.onclick=async()=>{posted.disabled=true;try{await api('/api/posted',{itemCode:c.itemCode,fingerprint:c.fingerprint});message('投稿済みとして履歴に保存しました。');await load()}catch(e){message(e.message);posted.disabled=!fresh(c)}};actions.append(open,copy,posted);card.append(actions,node('p','hint','ROOMで投稿が完了したら「投稿済みにする」を押してください。'));$('#cards').append(card)}$('#summary').textContent=`投稿済み ${done} / ${data.cards.length}　・　今すぐ準備できる ${ready}件`;$('#progress').textContent=busy?'最新情報を確認中…':`最終確認：${timeLabel(data.checked_at)}`}
async function load(){try{const data=await api('/api/state');if(pending&&data.request_id===pending){busy=false;pending='';message('最新情報を確認しました。商品を開き、本文をコピーしてROOMへ投稿できます。')}if(busy&&Date.now()-started>240000){busy=false;pending='';message('確認に時間がかかっています。少し待って画面を更新してください。古い情報での投稿はしないでください。')}render(data);$('#refresh').disabled=busy}catch(e){message(e.message)}}
$('#refresh').onclick=async()=>{busy=true;$('#refresh').disabled=true;try{const x=await api('/api/refresh',{});pending=x.request_id;started=Date.now();message(x.message);await load()}catch(e){busy=false;$('#refresh').disabled=false;message(e.message)}};
$('#reload').onclick=()=>connect();$('#import').onsubmit=async e=>{e.preventDefault();const form=new FormData(e.target);try{await api('/api/import',{itemName:form.get('itemName'),itemUrl:form.get('itemUrl')});message('既存のROOM投稿を履歴に登録しました。');e.target.reset()}catch(x){message(x.message)}};
async function connect(){try{const r=await fetch(base+'/api/session',{cache:'no-store'});token=(await r.json()).token;if(!token)throw Error();await load();clearInterval(timer);timer=setInterval(load,15000)}catch(e){$('#progress').textContent='Macとの接続待ち';message('このMacで「ROOMダッシュボードを起動.command」を開いてください。ブラウザからローカルネットワーク接続の許可を求められた場合は許可し、「画面を更新」を押してください。')}}connect();
