'use strict';
const testMode=new URLSearchParams(location.search).get('test')==='1';
const $=s=>document.querySelector(s),base=window.YUA_ROOM_API,labels={READY:'今日投稿OK',FAILED:'処理失敗',READY_TO_POST:'投稿準備OK',POSTED:'投稿済み',SOLD_OUT:'売り切れ',NEEDS_REVIEW:'原稿QA保留',READY_STALE:'原稿確認済み・最新商品情報の再確認待ち',GENERATION_MISSING:'原稿未取得',EXCLUDED:'対象外',DISCONTINUED:'販売終了'};let data,active=null,refreshing=false,poll;
const message=s=>$('#notice').textContent=s;
const time=t=>t?new Date(t).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'}):'未確認';
function node(tag,cls,text){const e=document.createElement(tag);e.className=cls;if(text!=null)e.textContent=text;return e}
function repeatTest(c){return testMode&&c.itemCode==='yua-cloud-test:001'&&c.status==='POSTED'&&c.action?.expires>Date.now()/1000}
function ready(c){const age=Date.now()-Date.parse(c.last_stock_checked_at);return !refreshing&&c.canPost&&age>=0&&age<900000&&c.action?.expires>Date.now()/1000}
function popup(command,payload,onSuccess,onError){if(active){message('開いている認証画面で操作を完了してください。');return false}const win=window.open(base+'/action','yua-room-action','popup,width=480,height=660');if(!win){message('このサイトのポップアップを許可して、もう一度押してください。');return false}const requestId=crypto.randomUUID();active={win,command,payload,requestId,onSuccess,onError};const timer=setInterval(()=>{if(!active||active.requestId!==requestId){clearInterval(timer);return}if(win.closed){const a=active;active=null;clearInterval(timer);a.onError('記録結果を確認できませんでした。「画面を更新」で確認してください。')}},500);return true}
window.addEventListener('message',e=>{if(!active||e.origin!==base||e.source!==active.win)return;if(e.data?.type==='yua-ready')active.win.postMessage({type:'yua-action',command:active.command,payload:active.payload,requestId:active.requestId},base);if(e.data?.requestId===active.requestId&&['yua-result','yua-error'].includes(e.data.type)){const a=active;active=null;if(e.data.type==='yua-result')a.onSuccess(e.data.result);else a.onError(e.data.error||'記録できませんでした')}});
function card(c){const el=node('article','card'),top=node('div','card-top'),image=node('img','image');image.alt=c.itemName;image.loading='lazy';try{const u=new URL(c.imageUrl);if(u.protocol==='https:'&&(u.hostname.endsWith('.rakuten.co.jp')||u.hostname.endsWith('.r10s.jp')))image.src=u.href}catch{}const meta=node('div','');meta.append(node('p','category',c.category),node('h2','name',c.itemName),node('p','shop',c.shopName));top.append(image,meta);el.append(top,node('p','price',Number(c.itemPrice).toLocaleString()+'円'),node('p','shipping',c.shippingInformation?.label||'送料は商品ページで確認'),node('p','hint','地域・種類別の条件は商品ページをご確認ください。'),node('span','badge',c.preparation_ready?'準備完了・投稿停止中':c.status==='READY_TO_POST'&&!ready(c)?'最新確認が必要':labels[c.status]||c.status),node('p','check-time','在庫確認：'+time(c.last_stock_checked_at)),node('div','body',c.roomText),node('p','tags',(c.hashtags||[]).join(' ')));
 el.append(node('p','hold-reason','理由：'+(c.hold_reason||'記録を確認してください')),node('p','next-action','次の処理：'+(c.next_action||'状態を確認')),node('p','check-time','原稿生成：'+time(c.generated_at)));
 const buttons=node('div','actions'),open=node('button','','楽天商品を開く'),copy=node('button','quiet','投稿文をコピー'),posted=node('button','posted-button',c.status==='POSTED'?'✓ 投稿済み':'✓ 投稿済みにする'),date=node('p','hint',c.posted_at?time(c.posted_at):'ROOMで投稿が完了したら押してください。');open.disabled=copy.disabled=posted.disabled=!ready(c);if(c.status==='POSTED')open.disabled=copy.disabled=false;if(repeatTest(c)){posted.disabled=false;posted.textContent='再記録（重複テスト）'}
 open.onclick=()=>{if(c.status!=='POSTED'&&!ready(c))return message('最新情報を確認してください');const u=new URL(c.itemUrl);if(u.protocol==='https:'&&u.hostname==='item.rakuten.co.jp')window.open(u.href,'_blank','noopener,noreferrer')};copy.onclick=async()=>{if(c.status!=='POSTED'&&!ready(c))return message('最新情報を確認してください');try{await navigator.clipboard.writeText(c.fullPostText);copy.textContent='コピーしました ✓';setTimeout(()=>copy.textContent='投稿文をコピー',1600)}catch{message('コピーできませんでした。ブラウザの権限をご確認ください。')}};
 posted.onclick=()=>{if(!ready(c)&&!repeatTest(c))return message('最新情報を確認してください');const started=popup('mark-posted',c.action,result=>{if(!['POSTED','already_posted'].includes(result.status)){posted.textContent='記録できませんでした';posted.disabled=false;return}c.status='POSTED';c.posted_at=result.posted_at;c.canPost=false;load();message(result.status==='already_posted'?'既に記録済みです。二重登録はありません。':'投稿済みとして記録しました。')},error=>{posted.textContent='記録できませんでした';posted.disabled=false;message(error)});if(started){posted.textContent='記録中…';posted.disabled=true}};buttons.append(open,copy,posted);el.append(buttons,date);return el}
function japanDay(stamp=new Date()){try{return new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(stamp))}catch{return null}}
function groups(){const rows=data.cards;return {ready:rows.filter(c=>['READY','READY_TO_POST'].includes(c.status)),review:rows.filter(c=>c.status==='NEEDS_REVIEW'),posted:rows.filter(c=>c.status==='POSTED'),stale:rows.filter(c=>c.status==='READY_STALE'&&!c.preparation_ready),missing:rows.filter(c=>c.status==='GENERATION_MISSING'),failed:rows.filter(c=>c.status==='FAILED'),other:rows.filter(c=>['SOLD_OUT','DISCONTINUED','EXCLUDED'].includes(c.status))}}
function summary(){const o=data.operations;if(!o){$('#summary').textContent='検証用表示';return}const box=$('#summary');box.replaceChildren();box.append(node('h2','','今日の運用状況'),node('p','plan',o.explanation));const grid=node('div','status-grid');for(const [label,value] of [['今日投稿可能',o.counts.READY],['目標5件まであと',o.shortage],['最新情報確認の対象',Math.max(0,o.counts.READY_STALE-(o.preparation?.prepared_count||0))],['原稿QA保留',o.counts.NEEDS_REVIEW],['無料修復可能（検証済み）',o.cards.filter(c=>c.free_repair_possible).length],['生成未完了',o.counts.GENERATION_MISSING],['対象外',o.counts.EXCLUDED],['処理失敗',o.counts.FAILED],['本日投稿済み',o.posted_today],['投稿後の反応確認',o.reaction_due??'未取得']]){const c=node('div','status-tile');c.append(node('span','',label),node('strong','',(value==='未取得'?value:value+'件')));grid.append(c)}box.append(grid,node('p','hint','投稿する直前に「最新情報を確認」を押してください。必要件数の商品情報だけを再確認します（有効期限15分）。新しい原稿は生成しません。確認対象件数は復活の保証ではありません。'));
 const warnings=node('div','operation-warnings');warnings.setAttribute('role','status');for(const w of o.warnings)warnings.append(node('p','',w));box.append(warnings);
 if(o.selection_diagnostics?.reason)box.append(node('p','plan','候補補充：'+o.selection_diagnostics.reason));
 const h=o.daily,health=node('details','health');health.open=true;health.append(node('summary','','日次処理の健康状態：'+h.status));for(const t of [`予定：${time(h.scheduled_at)}`,`開始：${h.started_at?time(h.started_at):'開始記録なし'} / 終了：${h.finished_at?time(h.finished_at):'終了記録なし'}`,`遅延：${h.delay_minutes==null?'不明':h.delay_minutes+'分'} / 本番反映：${h.production_reflected?'反映済み':'未反映'}`,`処理対象：${h.processed_count??'未記録'}件 / 保存時READY：${h.run_ready_count??'未記録'}件 / 保存時保留：${h.run_hold_count??'未記録'}件`,`途中成果READY：${h.intermediate_ready??0}件（期限切れ原稿を含む）`,`最終正常処理日：${h.last_success_date||'確認できません'}`,h.original_run_outcome?`元run：${h.original_run_outcome}（救済後の状態と区別）`:'',h.waiting||'',h.reason||'記録された失敗理由なし'])if(t)health.append(node('p','',t));box.append(health,node('p','check-time',`画面再集計：${time(o.as_of)} / 保存原稿日：${o.draft_date} / 商品情報確認：${time(o.last_product_check)}`));}
function renderGroups(){summary();window.renderRoomPage?.()}
async function load(){if(!/^https:\/\/[a-z0-9.-]+\.workers\.dev$/.test(base||'')){message('クラウド接続の準備中です。');return}try{const r=await fetch(base+(testMode?'/test-state':'/state'),{cache:'no-store'});if(!r.ok)throw Error();data=await r.json();if($('#notice').textContent.startsWith('読み込めませんでした'))message('');renderGroups();$('#progress').textContent='商品情報確認：'+time(data.checked_at||(data.cards||[]).map(c=>c.last_stock_checked_at).filter(t=>Number.isFinite(Date.parse(t))).sort().at(-1))}catch{message('読み込めませんでした。少し待って「画面を更新」を押してください。')}}
if(testMode){document.querySelector('h1').textContent='動作確認専用・実際のROOM投稿はしません';$('#refresh').hidden=true;}
$('#reload').onclick=load;$('#refresh').onclick=()=>{popup('refresh',{},()=>{refreshing=true;$('#refresh').disabled=true;message('最新情報を確認しています。通常1〜2分ほどかかります。');const old=data?.request_id,start=Date.now();poll=setInterval(async()=>{await load();if(data?.request_id!==old&&data?.cards.some(c=>c.action?.expires>Date.now()/1000)||Date.now()-start>240000){clearInterval(poll);refreshing=false;$('#refresh').disabled=false;await load();message(Date.now()-start>240000?'確認結果を取得できませんでした。しばらくして画面を更新してください。':'最新確認が完了しました。')}},12000)},message)};load();

window.addEventListener('focus',()=>{if(!active)load()});

setInterval(()=>{if(!active&&!refreshing)load()},30000);
