'use strict';
const testMode=new URLSearchParams(location.search).get('test')==='1';
const $=s=>document.querySelector(s),base=window.YUA_ROOM_API,labels={READY_TO_POST:'投稿準備OK',POSTED:'投稿済み',SOLD_OUT:'売り切れ',NEEDS_REVIEW:'要確認',DISCONTINUED:'販売終了'};let data,active=null,refreshing=false,poll;
const message=s=>$('#notice').textContent=s;
const time=t=>t?new Date(t).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'}):'未確認';
function node(tag,cls,text){const e=document.createElement(tag);e.className=cls;if(text!=null)e.textContent=text;return e}
function repeatTest(c){return testMode&&c.itemCode==='yua-cloud-test:001'&&c.status==='POSTED'&&c.action?.expires>Date.now()/1000}
function ready(c){const age=Date.now()-Date.parse(c.last_stock_checked_at);return !refreshing&&c.canPost&&age>=0&&age<900000&&c.action?.expires>Date.now()/1000}
function popup(command,payload,onSuccess,onError){if(active){message('開いている認証画面で操作を完了してください。');return false}const win=window.open(base+'/action','yua-room-action','popup,width=480,height=660');if(!win){message('このサイトのポップアップを許可して、もう一度押してください。');return false}const requestId=crypto.randomUUID();active={win,command,payload,requestId,onSuccess,onError};const timer=setInterval(()=>{if(!active||active.requestId!==requestId){clearInterval(timer);return}if(win.closed){const a=active;active=null;clearInterval(timer);a.onError('記録結果を確認できませんでした。「画面を更新」で確認してください。')}},500);return true}
window.addEventListener('message',e=>{if(!active||e.origin!==base||e.source!==active.win)return;if(e.data?.type==='yua-ready')active.win.postMessage({type:'yua-action',command:active.command,payload:active.payload,requestId:active.requestId},base);if(e.data?.requestId===active.requestId&&['yua-result','yua-error'].includes(e.data.type)){const a=active;active=null;if(e.data.type==='yua-result')a.onSuccess(e.data.result);else a.onError(e.data.error||'記録できませんでした')}});
function card(c){const el=node('article','card'),top=node('div','card-top'),image=node('img','image');image.alt=c.itemName;image.loading='lazy';try{const u=new URL(c.imageUrl);if(u.protocol==='https:'&&(u.hostname.endsWith('.rakuten.co.jp')||u.hostname.endsWith('.r10s.jp')))image.src=u.href}catch{}const meta=node('div','');meta.append(node('p','category',c.category),node('h2','name',c.itemName),node('p','shop',c.shopName));top.append(image,meta);el.append(top,node('p','price',Number(c.itemPrice).toLocaleString()+'円'),node('p','shipping',c.shippingInformation?.label||'送料は商品ページで確認'),node('p','hint','地域・種類別の条件は商品ページをご確認ください。'),node('span','badge',c.status==='READY_TO_POST'&&!ready(c)?'最新確認が必要':labels[c.status]||c.status),node('p','check-time','在庫確認：'+time(c.last_stock_checked_at)),node('div','body',c.roomText),node('p','tags',(c.hashtags||[]).join(' ')));
 const buttons=node('div','actions'),open=node('button','','楽天商品を開く'),copy=node('button','quiet','投稿文をコピー'),posted=node('button','posted-button',c.status==='POSTED'?'✓ 投稿済み':'✓ 投稿済みにする'),date=node('p','hint',c.posted_at?time(c.posted_at):'ROOMで投稿が完了したら押してください。');open.disabled=copy.disabled=posted.disabled=!ready(c);if(c.status==='POSTED')open.disabled=copy.disabled=false;if(repeatTest(c)){posted.disabled=false;posted.textContent='再記録（重複テスト）'}
 open.onclick=()=>{if(c.status!=='POSTED'&&!ready(c))return message('最新情報を確認してください');const u=new URL(c.itemUrl);if(u.protocol==='https:'&&u.hostname==='item.rakuten.co.jp')window.open(u.href,'_blank','noopener,noreferrer')};copy.onclick=async()=>{if(c.status!=='POSTED'&&!ready(c))return message('最新情報を確認してください');try{await navigator.clipboard.writeText(c.fullPostText);copy.textContent='コピーしました ✓';setTimeout(()=>copy.textContent='投稿文をコピー',1600)}catch{message('コピーできませんでした。ブラウザの権限をご確認ください。')}};
 posted.onclick=()=>{if(!ready(c)&&!repeatTest(c))return message('最新情報を確認してください');const started=popup('mark-posted',c.action,result=>{if(!['POSTED','already_posted'].includes(result.status)){posted.textContent='記録できませんでした';posted.disabled=false;return}c.status='POSTED';c.posted_at=result.posted_at;c.canPost=false;renderGroups();message(result.status==='already_posted'?'既に記録済みです。二重登録はありません。':'投稿済みとして記録しました。')},error=>{posted.textContent='記録できませんでした';posted.disabled=false;message(error)});if(started){posted.textContent='記録中…';posted.disabled=true}};buttons.append(open,copy,posted);el.append(buttons,date);return el}
function groups(){const today=data.cards.filter(c=>!c.draft_date||c.draft_date===data.date);return {ready:today.filter(c=>c.status==='READY_TO_POST'),review:data.cards.filter(c=>c.status==='NEEDS_REVIEW'),posted:today.filter(c=>c.status==='POSTED'),backlog:data.cards.filter(c=>c.draft_date&&c.draft_date!==data.date&&c.status==='READY_TO_POST'),other:data.cards.filter(c=>['SOLD_OUT','DISCONTINUED'].includes(c.status))}}
function summary(){const g=groups();$('#summary').textContent=`${data.date}分：今日投稿できる商品 ${g.ready.length+g.posted.length} / 5（投稿済みを含む） ・ 投稿済み ${g.posted.length}件 ・ 投稿準備OK ${g.ready.length}件 ・ 要確認 ${g.review.length}件 ・ 不足 ${Math.max(0,5-g.ready.length-g.posted.length)}件（操作前に最新確認）`;const count=document.querySelector('h1 span');if(count)count.textContent=g.ready.length+'商品'}
function renderGroups(){const g=groups();$('#cards').replaceChildren(...g.ready.map(card));for(const [id,title,rows] of [['review','要確認',g.review],['backlog','未投稿の商品',g.backlog],['posted','投稿済み',g.posted],['unavailable','売り切れ・販売終了',g.other]]){let el=$('#'+id);if(!el){el=node('section','');el.id=id;document.querySelector('footer').before(el)}el.replaceChildren(...(rows.length?[node('h2','',title+'：'+rows.length+'件'),...rows.map(card)]:[]))}summary()}
async function load(){if(!/^https:\/\/[a-z0-9.-]+\.workers\.dev$/.test(base||'')){message('クラウド接続の準備中です。');return}try{const r=await fetch(base+(testMode?'/test-state':'/state'),{cache:'no-store'});if(!r.ok)throw Error();data=await r.json();if($('#notice').textContent.startsWith('読み込めませんでした'))message('');renderGroups();$('#progress').textContent='最終確認：'+time(data.checked_at)}catch{message('読み込めませんでした。少し待って「画面を更新」を押してください。')}}
if(testMode){document.querySelector('h1').textContent='動作確認専用・実際のROOM投稿はしません';$('#refresh').hidden=true;}
$('#reload').onclick=load;$('#refresh').onclick=()=>{popup('refresh',{},()=>{refreshing=true;$('#refresh').disabled=true;message('最新情報を確認しています。通常1〜2分ほどかかります。');const old=data?.request_id,start=Date.now();poll=setInterval(async()=>{await load();if(data?.request_id!==old&&data?.cards.some(c=>c.action?.expires>Date.now()/1000)||Date.now()-start>240000){clearInterval(poll);refreshing=false;$('#refresh').disabled=false;await load();message(Date.now()-start>240000?'確認結果を取得できませんでした。しばらくして画面を更新してください。':'最新確認が完了しました。')}},12000)},message)};load();

window.addEventListener('focus',()=>{if(!active)load()});
