'use strict';
const fieldLabels={likes:'♡ いいね',comments:'💬 コメント',sales_count:'売上件数',sales_amount:'売上金額（円）',reward_amount:'報酬（円）',clicks:'クリック'};
let reactionRows=[],reactionEdits=new Map(),reactionBusy=false,reactionRequest=null;
const metricValue=v=>v==null?'—':String(v);
const dateShort=t=>t?new Date(t).toLocaleDateString('ja-JP',{timeZone:'Asia/Tokyo',month:'numeric',day:'numeric'}):'投稿日不明';
const deltaLabel=v=>v==null?'':`（${v>0?'+':''}${v}）`;
const checkedAt=r=>r.last_checked_at||r.last_updated_at;
function reactionAge(r){return r.posted_at?(Date.now()-Date.parse(r.posted_at))/86400000:null}
function needsReaction(r){const age=reactionAge(r),last=Date.parse(checkedAt(r));if(age!=null&&age>14)return false;return r.likes==null||r.comments==null||(!Number.isFinite(last)||Date.now()-last>=86400000)&&((age!=null&&age<=7)||r.comments>0||r.likes_delta>0||r.comments_delta>0)}
function reactionRank(r){const age=reactionAge(r);return age!=null&&age>14?5:age!=null&&age<=7?0:r.likes==null||r.comments==null?1:r.comments>0?2:r.roomPerformanceScore>=60?3:4}
function editing(r){if(!reactionEdits.has(r.itemCode))reactionEdits.set(r.itemCode,{values:{...r},correction:false,confirmed:false,report:false});return reactionEdits.get(r.itemCode)}
function reactionChanges(r){const e=reactionEdits.get(r.itemCode);if(!e)return null;const changes={};for(const key of Object.keys(fieldLabels))if((e.values[key]??null)!==(r[key]??null))changes[key]=e.values[key]??null;const note=e.values.comment_text??'',noteChanged=note!==(r.comment_text??'');if(!Object.keys(changes).length&&!noteChanged&&!e.confirmed)return null;return {itemCode:r.itemCode,changes,expected_updated_at:r.last_updated_at,correction:e.correction,report_confirmed:e.report,confirm_checked:e.confirmed,...(noteChanged?{comment_text:note}:{})}}
function renderSummary(){let changed=0,likes=0,comments=0,unknown=false;for(const r of reactionRows){const c=reactionChanges(r);if(!c)continue;changed++;for(const k of ['likes','comments'])if(k in c.changes){if(r[k]==null||c.changes[k]==null)unknown=true;else if(k==='likes')likes+=c.changes[k]-r[k];else comments+=c.changes[k]-r[k]}}
 batchSummary.textContent=`変更${changed}商品　♡ ${likes>=0?'+':''}${likes}　💬 ${comments>=0?'+':''}${comments}${unknown?'（初回確認は差分なし）':''}`;
 batchSave.disabled=reactionBusy||!changed;batchSave.textContent=reactionBusy?'保存・分析中…':'変更した反応をまとめて保存';
}
function reactionCard(r){const e=editing(r),card=node('article','reaction-card'),head=node('div','reaction-head'),image=node('img','reaction-image');image.alt='';image.loading='lazy';try{const u=new URL(r.imageUrl);if(u.protocol==='https:'&&(u.hostname.endsWith('.rakuten.co.jp')||u.hostname.endsWith('.r10s.jp')))image.src=u.href;else image.hidden=true}catch{image.hidden=true}
 const meta=node('div','reaction-meta');meta.append(node('h3','reaction-name',r.itemName),node('p','hint',dateShort(r.posted_at)+(r.posted_at?'投稿':'')+' ・ '+(r.category||'カテゴリ未記録')));head.append(image,meta);card.append(head);
 const warn=node('p','reaction-warning'),badge=node('p','hint'),foot=node('p','hint','前回確認：'+time(checkedAt(r))),controls={};warn.setAttribute('role','status');
 const update=(invalidate=true)=>{if(invalidate)reactionRequest=null;const down=['likes','comments'].some(k=>r[k]!=null&&(e.values[k]==null||e.values[k]<r[k]));warn.textContent=down&&!e.correction?'保存済みの数値より少なくなっています':'';badge.textContent=(r.comments>0?'💬 コメントあり ・ ':'')+(e.confirmed?'確認済み（保存前）':r.likes==null||r.comments==null?'未確認':needsReaction(r)?'確認時期':'確認済み');renderSummary()};
 for(const [k,label] of [['likes','♡ いいね'],['comments','💬 コメント']]){
  const row=node('div','reaction-counter'),minus=node('button','quiet','−1'),plus=node('button','','＋1'),middle=node('label','',label),input=node('input','');input.type='number';input.inputMode='numeric';input.min='0';input.max='1000000000';input.step='1';input.value=e.values[k]??'';input.placeholder='—';input.setAttribute('aria-label',label);const delta=node('span','reaction-delta',deltaLabel(r[k+'_delta']));middle.append(input,delta);minus.type=plus.type='button';minus.setAttribute('aria-label',label+'を1減らす');plus.setAttribute('aria-label',label+'を1増やす');
  const refresh=()=>{input.value=e.values[k]??'';minus.disabled=reactionBusy||e.values[k]==null||e.values[k]<=0;update()};minus.onclick=()=>{if(e.values[k]!=null)e.values[k]=Math.max(0,e.values[k]-1);refresh()};plus.onclick=()=>{e.values[k]=e.values[k]==null?1:e.values[k]+1;refresh()};input.oninput=()=>{e.values[k]=input.value===''?null:Number(input.value);minus.disabled=e.values[k]==null||e.values[k]<=0;update()};minus.disabled=e.values[k]==null||e.values[k]<=0;row.append(minus,middle,plus);card.append(row);controls[k]=input;
 }
 const tools=node('div','reaction-tools'),undo=node('button','quiet','元に戻す'),confirm=node('button','quiet','変化なしを確認');undo.onclick=()=>{reactionEdits.delete(r.itemCode);card.replaceWith(reactionCard(r));reactionRequest=null;renderSummary()};confirm.disabled=r.likes==null||r.comments==null;confirm.onclick=()=>{e.confirmed=!e.confirmed;confirm.textContent=e.confirmed?'確認を取り消す':'変化なしを確認';update()};tools.append(undo,confirm);card.append(tools,warn);
 const correctionLabel=node('label','confirm','数値を修正する（減少を許可）'),correction=node('input','');correction.type='checkbox';correction.checked=e.correction;correction.onchange=()=>{e.correction=correction.checked;update()};correctionLabel.prepend(correction);
 const more=node('details','reaction-more');more.append(node('summary','','訂正・コメント・売上'),correctionLabel);
 const commentLabel=node('label','','ROOMで確認したコメント（任意）'),comment=node('textarea','');comment.maxLength=1000;comment.rows=2;comment.value=e.values.comment_text??'';comment.placeholder='ご自身で確認したコメントだけ貼り付け';comment.oninput=()=>{e.values.comment_text=comment.value;update()};commentLabel.append(comment);more.append(commentLabel);
 if(r.reply_draft?.text)more.append(node('p','hint','返信案（自動送信はしません）：'+r.reply_draft.text));else if(r.reply_draft?.status==='NEEDS_REVIEW')more.append(node('p','hint','返信前に質問内容の事実確認が必要です。'));
 const sales=node('details','');sales.append(node('summary','','公式レポートの売上・クリック'),node('p','hint','商品別に帰属が確認できる累計だけ入力。未取得は空欄のまま。'));
 for(const k of ['sales_count','sales_amount','reward_amount','clicks']){const label=node('label','',fieldLabels[k]),input=node('input','');input.type='number';input.inputMode=k.endsWith('_amount')?'decimal':'numeric';input.min='0';input.max='1000000000';input.step=k.endsWith('_amount')?'.01':'1';input.value=e.values[k]??'';input.placeholder='—';input.oninput=()=>{e.values[k]=input.value===''?null:Number(input.value);update()};label.append(input);sales.append(label)}
 const reportLabel=node('label','confirm','公式レポートの商品別累計を確認しました'),report=node('input','');report.type='checkbox';report.checked=e.report;report.onchange=()=>{e.report=report.checked;update()};reportLabel.prepend(report);sales.append(reportLabel);more.append(sales);card.append(more,badge,foot);update(false);return card;
}
function renderReactions(){const sorted=[...reactionRows].sort((a,b)=>reactionRank(a)-reactionRank(b)||(Date.parse(b.posted_at)||0)-(Date.parse(a.posted_at)||0));const today=sorted.filter(needsReaction),other=sorted.filter(r=>!needsReaction(r));todayList.replaceChildren(...today.map(reactionCard));todayTitle.textContent=`今日の反応確認 ${today.length}商品`;if(!today.length)todayList.append(node('p','hint','今日の確認対象はありません。1日1回程度で十分です。'));older.replaceChildren(node('summary','',`過去の商品・確認済み ${other.length}商品`),...other.map(reactionCard));renderSummary()}
const feedback=node('section','feedback'),login=node('button','quiet','反応を表示・更新（GitHubログイン）'),todayTitle=node('h3','','今日の反応確認'),todayList=node('div','reaction-list'),older=node('details','reaction-older'),batchBar=node('div','reaction-savebar'),batchSummary=node('p',''),batchSave=node('button','','変更した反応をまとめて保存'),batchStatus=node('p','hint');batchStatus.setAttribute('role','status');batchBar.append(batchSummary,batchSave,batchStatus);feedback.append(node('h2','','反応を更新'),node('p','hint','ROOMで確認した数を入力。1日1回程度で大丈夫です。未確認は「—」、確認済み0件は「0」。数値は直接入力もできます。'),login,todayTitle,todayList,older,batchBar);document.querySelector('footer').before(feedback);renderSummary();
login.onclick=()=>{if(reactionRows.some(r=>reactionChanges(r)))return message('保存前の変更があります。保存または元に戻してから更新してください。');popup('performance-read',{},result=>{reactionRows=result.items;reactionEdits.clear();renderReactions();login.textContent='反応データを再読込'},message)};
batchSave.onclick=()=>{if(reactionBusy)return;const updates=reactionRows.map(reactionChanges).filter(Boolean);if(!updates.length)return;
 for(const u of updates){const old=reactionRows.find(r=>r.itemCode===u.itemCode);if(['likes','comments'].some(k=>k in u.changes&&old[k]!=null&&(u.changes[k]==null||u.changes[k]<old[k]))&&!u.correction){batchStatus.textContent='保存済みの数値より少なくなっています。訂正する場合は「数値を修正する」を選んでください。';return}for(const [k,v] of Object.entries(u.changes))if(v!=null&&(!Number.isFinite(v)||v<0||v>1e9||(!k.endsWith('_amount')&&!Number.isInteger(v)))){batchStatus.textContent='0以上の正しい数値を入力してください。';return}}
 reactionRequest??=crypto.randomUUID();const lock=v=>{reactionBusy=v;feedback.querySelectorAll('button,input,textarea').forEach(x=>x.disabled=v);renderSummary()};lock(true);batchStatus.textContent='保存と分析を実行しています…';
 const started=popup('record-performance-batch',{updates,request_id:reactionRequest},result=>{reactionRows=result.items;reactionEdits.clear();reactionRequest=null;lock(false);renderReactions();batchStatus.textContent=result.status==='UNCHANGED'?'既に保存済みです。二重更新はありません。':'保存・分析が完了しました。翌朝の選定へ自動反映します。'},error=>{lock(false);renderReactions();batchStatus.textContent=error+' 入力内容は保持しています。'});if(!started){lock(false);renderReactions();batchStatus.textContent='認証画面を開けませんでした。もう一度お試しください。'};
};
